#!/bin/sh

if ! test -d env; then
    virtualenv env;
    source env/bin/activate;
    if test -f requirements.txt; then
        pip install -r requirements.txt;
    fi;
else
    source env/bin/activate;
fi;

export PYTHONPATH=$PYTHONPATH:src/back
